{
 "title": "Loki",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fail2ban",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/fail2ban.log\",job=\"fail2ban\",service_name=\"fail2ban\"}"
    }
   ]
  },
  {
   "title": "RA Denied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"postfix\"} |= \"denied\" [5m])"
    }
   ]
  },
  {
   "title": "Postfix",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"postfix\",service_name=\"postfix\"}"
    }
   ]
  }
 ]
}