global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['grafana-node_exporter-1:9100']  # or your host IP if not on Docker for Windows/macOS
